version: '3.9'

services:
  database:
    image: mysql:latest
    container_name: sexta-database
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_ROOT_PASSWORD=123
      - TZ=America/Sao_Paulo
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
